package SysY.LexicAnalysis;

public enum TokenKey {
    IDENFR,//Ident
    INTCON,//IntConst
    STRCON,//FormatString
    MAINTK,//main
    CONSTTK,//const
    INTTK,//int
    BREAKTK,//break
    CONTINUETK,//continue
    IFTK,//if
    ELSETK,//else
    NOT,//!
    AND,//&&
    OR,//||
    WHILETK,//while
    GETINTTK,//getint
    PRINTFTK,//printf
    RETURNTK,//return
    PLUS,//+
    MINU,//-
    VOIDTK,//void
    MULT,//*
    DIV,///
    MOD,//%
    LSS,//<
    LEQ,//<=
    GRE,//>
    GEQ,//>=
    EQL,//==
    NEQ,//!=
    ASSIGN,//=
    SEMICN,//;
    COMMA,//,
    LPARENT,//(
    RPARENT,//)
    LBRACK,//[
    RBRACK,//]
    LBRACE,//{
    RBRACE,//}
}
